/**
 * Real project dataset — authored from Daniel's GitHub (github.com/dbisina).
 * Generated by scripts/assemble-projects.mjs; edit in /studio (this is the
 * seed the Studio store hydrates from).
 */
export type ProjectKind = "flagship" | "hackathon" | "personal";

export interface FeaturedProject {
  slug: string;
  index: string;
  name: string;
  tag: string;
  blurb: string;
  gradient: string;
  side: "engineering" | "business";
  /** Routes to a dedicated listing page (hackathons) or gets flagship billing.
   * Unset = a regular system/venture on the plain projects page. */
  kind?: ProjectKind;
  /** Seeded placeholder photography until real project imagery is uploaded. */
  image: string;
}

export const ALL_PROJECTS: FeaturedProject[] = [
  {
    "slug": "relay",
    "image": "https://picsum.photos/seed/tariwei-relay/1024/704",
    "index": "01",
    "name": "Relay",
    "tag": "SYSTEMS · AGENT INFRA",
    "blurb": "A vendor-neutral orchestrator that hands off in-flight work between AI coding agents using signed continuation contracts.",
    "gradient": "linear-gradient(155deg, #2a2a30 0%, #131316 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "flagship"
  },
  {
    "slug": "olddeus",
    "image": "https://picsum.photos/seed/tariwei-olddeus/1024/704",
    "index": "02",
    "name": "oldDeus",
    "tag": "FLAGSHIP · AUTONOMOUS OPS",
    "blurb": "The autonomous agent swarm that runs DeusX Technologies day to day — leads, sales, marketing, calls, and a weekly founder briefing, with zero human input.",
    "gradient": "linear-gradient(155deg, #23303a 0%, #121a20 60%, #0b0b0c 100%)",
    "side": "business",
    "kind": "flagship"
  },
  {
    "slug": "team-intuition-engine",
    "image": "https://picsum.photos/seed/tariwei-team-intuition-engine/1024/704",
    "index": "03",
    "name": "Team Intuition Engine",
    "tag": "SYSTEMS · ESPORTS ANALYTICS",
    "blurb": "An AI analyst and coach that turns official GRID match data into advanced metrics, what-if simulations, and live strategic guidance for League of Legends and VALORANT.",
    "gradient": "linear-gradient(155deg, #222a30 0%, #14181c 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "hackathon"
  },
  {
    "slug": "supportgenius",
    "image": "https://picsum.photos/seed/tariwei-supportgenius/1024/704",
    "index": "04",
    "name": "SupportGenius",
    "tag": "AI · AGENT ORCHESTRATION",
    "blurb": "A multi-agent eCommerce support system on Elasticsearch Agent Builder that resolves tickets through either a single autonomous agent or a six-agent pipeline with adversarial peer review.",
    "gradient": "linear-gradient(155deg, #2c2436 0%, #171220 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "hackathon"
  },
  {
    "slug": "sentinel-llm-observability",
    "image": "https://picsum.photos/seed/tariwei-sentinel-llm-observability/1024/704",
    "index": "05",
    "name": "Sentinel",
    "tag": "SYSTEMS · LLM OBSERVABILITY",
    "blurb": "Sentinel wraps LLM calls as FastAPI middleware, tracks 16+ metrics per request, and turns Z-score anomalies into Datadog incidents with Gemini-written root cause analysis.",
    "gradient": "linear-gradient(155deg, #3a2a22 0%, #1e1712 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "hackathon"
  },
  {
    "slug": "verdescore",
    "image": "https://picsum.photos/seed/tariwei-verdescore/1024/704",
    "index": "06",
    "name": "VerdeScore",
    "tag": "HACKATHON · FINTECH AI",
    "blurb": "Scores green loans for EU Taxonomy and LMA compliance in milliseconds instead of days.",
    "gradient": "linear-gradient(155deg, #223530 0%, #121e1a 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "hackathon"
  },
  {
    "slug": "souschef",
    "image": "https://picsum.photos/seed/tariwei-souschef/1024/704",
    "index": "07",
    "name": "SousChef",
    "tag": "HACKATHON · AI MOBILE",
    "blurb": "Turns any cooking video into a structured, voice-guided recipe you can follow hands-free.",
    "gradient": "linear-gradient(155deg, #33222e 0%, #1d121a 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "hackathon"
  },
  {
    "slug": "ai-cinematography-editing",
    "image": "https://picsum.photos/seed/tariwei-ai-cinematography-editing/1024/704",
    "index": "08",
    "name": "AI Cinematography & Editing System",
    "tag": "SYSTEMS · AI VIDEO",
    "blurb": "An AI post-production system that learns a creator's editing style and turns raw fashion footage into a publish-ready 9:16 cut in minutes.",
    "gradient": "linear-gradient(155deg, #383023 0%, #201b12 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "personal"
  },
  {
    "slug": "rimuru-os",
    "image": "https://picsum.photos/seed/tariwei-rimuru-os/1024/704",
    "index": "09",
    "name": "Rimuru OS",
    "tag": "SYSTEMS · AI-NATIVE OS",
    "blurb": "A local-only, AI-native Linux distribution where you control the desktop by describing what you want instead of clicking through it.",
    "gradient": "linear-gradient(155deg, #35232a 0%, #1e1216 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "personal"
  },
  {
    "slug": "ijaw-language-curator",
    "image": "https://picsum.photos/seed/tariwei-ijaw-language-curator/1024/704",
    "index": "10",
    "name": "Ijaw Language Curator",
    "tag": "BUSINESS · LANGUAGE TECH",
    "blurb": "A collaborative platform where AI drafts Ijaw dictionary entries and the community corrects them into a verified, dialect-tagged dataset for language learning.",
    "gradient": "linear-gradient(155deg, #1f2b33 0%, #12181d 60%, #0b0b0c 100%)",
    "side": "business",
    "kind": "personal"
  },
  {
    "slug": "vizer",
    "image": "https://picsum.photos/seed/tariwei-vizer/1024/704",
    "index": "11",
    "name": "Vizer",
    "tag": "BUSINESS · TRAVEL",
    "blurb": "Global visa information made searchable — requirements and steps organized by destination.",
    "gradient": "linear-gradient(155deg, #2a2a30 0%, #131316 60%, #0b0b0c 100%)",
    "side": "business",
    "kind": "personal"
  },
  {
    "slug": "capsule-obd",
    "image": "https://picsum.photos/seed/tariwei-capsule-obd/1024/704",
    "index": "12",
    "name": "Capsule OBD",
    "tag": "PERSONAL · VEHICLE DIAGNOSTICS",
    "blurb": "A cross-platform OBD/CAN diagnostic tool built to match manufacturer-level scan tools using only open standards.",
    "gradient": "linear-gradient(155deg, #23303a 0%, #121a20 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "personal"
  },
  {
    "slug": "jobhive",
    "image": "https://picsum.photos/seed/tariwei-jobhive/1024/704",
    "index": "13",
    "name": "JobHive",
    "tag": "PERSONAL · AGENT SWARM",
    "blurb": "A swarm of AI agents that finds jobs, tailors your CV per posting, applies, and tracks every response.",
    "gradient": "linear-gradient(155deg, #222a30 0%, #14181c 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "personal"
  },
  {
    "slug": "uto-cms",
    "image": "https://picsum.photos/seed/tariwei-uto-cms/1024/704",
    "index": "14",
    "name": "UTO CMS",
    "tag": "PERSONAL · DEV TOOLING",
    "blurb": "A headless, API-first CMS built as a personal monorepo library — deploy once, customize per project, no SaaS lock-in.",
    "gradient": "linear-gradient(155deg, #2c2436 0%, #171220 60%, #0b0b0c 100%)",
    "side": "engineering",
    "kind": "personal"
  },
  {
    "slug": "uhop",
    "image": "https://picsum.photos/seed/tariwei-uhop/1024/704",
    "index": "15",
    "name": "UHOP",
    "tag": "SYSTEMS · GPU RUNTIME",
    "blurb": "A universal hardware optimization runtime that unifies GPU acceleration across CUDA, ROCm, Metal and OpenCL behind one decorator.",
    "gradient": "linear-gradient(155deg, #3a2a22 0%, #1e1712 60%, #0b0b0c 100%)",
    "side": "engineering"
  },
  {
    "slug": "airfree-geospatial",
    "image": "https://picsum.photos/seed/tariwei-airfree-geospatial/1024/704",
    "index": "16",
    "name": "Airfree Geospatial",
    "tag": "WEB · CMS INFRA",
    "blurb": "A marketing site for an Australian geospatial consultancy with a custom Redis-backed CMS that lets non-technical staff edit content live, no code required.",
    "gradient": "linear-gradient(155deg, #223530 0%, #121e1a 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "hebron-hotels-suites",
    "image": "https://picsum.photos/seed/tariwei-hebron-hotels-suites/1024/704",
    "index": "17",
    "name": "Hebron Hotels & Suites",
    "tag": "BUSINESS · HOSPITALITY",
    "blurb": "A booking website and admin platform for a luxury hotel in Owerri, letting guests check live room availability and pay online while staff run every reservation from one dashboard.",
    "gradient": "linear-gradient(155deg, #33222e 0%, #1d121a 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "mamazee",
    "image": "https://picsum.photos/seed/tariwei-mamazee/1024/704",
    "index": "18",
    "name": "Mamazee",
    "tag": "BUSINESS · ECOMMERCE",
    "blurb": "An online storefront for a Nigerian grocery brand, selling pantry staples, spices, snacks, and beauty products with card checkout and a no-code admin for stock.",
    "gradient": "linear-gradient(155deg, #383023 0%, #201b12 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "wayfarian-adventures",
    "image": "https://picsum.photos/seed/tariwei-wayfarian-adventures/1024/704",
    "index": "19",
    "name": "Wayfarian Adventures",
    "tag": "BUSINESS · TRAVEL",
    "blurb": "A mobile app and backend that lets small groups plan a trip, track each other live on the map, and keep the route, stats, and photos together afterward.",
    "gradient": "linear-gradient(155deg, #35232a 0%, #1e1216 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "oldtime-power-church",
    "image": "https://picsum.photos/seed/tariwei-oldtime-power-church/1024/704",
    "index": "20",
    "name": "Old Time Power Church",
    "tag": "BUSINESS · COMMUNITY",
    "blurb": "A full-stack website for a church community, built so non-technical staff can update it themselves.",
    "gradient": "linear-gradient(155deg, #1f2b33 0%, #12181d 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "arimart",
    "image": "https://picsum.photos/seed/tariwei-arimart/1024/704",
    "index": "21",
    "name": "Arimart",
    "tag": "BUSINESS · ECOMMERCE",
    "blurb": "African grocery e-commerce, wholesale and recipe platform built for the UAE diaspora market.",
    "gradient": "linear-gradient(155deg, #2a2a30 0%, #131316 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "jenjay-foundation",
    "image": "https://picsum.photos/seed/tariwei-jenjay-foundation/1024/704",
    "index": "22",
    "name": "JenJay Foundation",
    "tag": "BUSINESS · NONPROFIT",
    "blurb": "A donation and outreach website for a Lagos-based nonprofit improving lives across rural and riverine communities.",
    "gradient": "linear-gradient(155deg, #23303a 0%, #121a20 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "serveme",
    "image": "https://picsum.photos/seed/tariwei-serveme/1024/704",
    "index": "23",
    "name": "ServeMe",
    "tag": "BUSINESS · SERVICES MARKETPLACE",
    "blurb": "A services marketplace where an AI layer helps clients describe what they need and matches them to the right provider.",
    "gradient": "linear-gradient(155deg, #222a30 0%, #14181c 60%, #0b0b0c 100%)",
    "side": "business"
  },
  {
    "slug": "luvsallure",
    "image": "https://picsum.photos/seed/tariwei-luvsallure/1024/704",
    "index": "24",
    "name": "Luv's Allure",
    "tag": "BUSINESS · ECOMMERCE",
    "blurb": "A women's clothing e-commerce site backed by a custom Node.js API layer in front of Shopify's Storefront API.",
    "gradient": "linear-gradient(155deg, #2c2436 0%, #171220 60%, #0b0b0c 100%)",
    "side": "business"
  }
];

export const FEATURED_PROJECTS = ALL_PROJECTS.slice(0, 3);
