import { ghJson, parseOwnerRepo } from "./github-knowledge";
import { nextGeminiKey, poolSize, reportGeminiKeyError } from "./key-pool";
import { setRepoIndexRow, type RepoDoc } from "@/lib/db";

/**
 * "Graphify" — builds a deep, multi-doc knowledge pack for a project's
 * GitHub repo so Rimuru can answer real questions about the codebase, not
 * just recite the one-liner. Triggered from the Studio's Graphify button
 * (POST /api/repo-index), runs in the background on the persistent Node
 * server (Railway standalone — a fire-and-forget promise survives the
 * request), and lands in the repo_index table where the get_repo_doc tool
 * reads it back.
 *
 * The pack: LLM-written docs (architecture overview, tech stack, module
 * map, per-module deep dives) generated by Gemini from the repo's actual
 * README, manifests, file tree and sampled sources — plus the raw tree and
 * README verbatim. If no Gemini key is configured (or every call fails),
 * the raw docs still land, so the pack degrades to "informed" instead of
 * "absent", matching the rest of the stack's env-gated graceful-degrade
 * rule (db.ts, notify.ts, upload/route.ts).
 */

const DOC_MODEL = "gemini-2.5-flash"; // bulk summarization — the workhorse model, not the chat one
const MAX_TREE_PATHS = 800; // paths shown to the LLM / stored in the tree doc
const MAX_KEY_FILES = 12;
const MAX_FILE_BYTES = 8 * 1024;
const MAX_MODULE_DOCS = 6;
const MAX_MODULE_SAMPLE_FILES = 2;

// manifests / configs / entry points worth reading verbatim, in priority order
const KEY_FILE_PATTERNS: RegExp[] = [
  /^package\.json$/,
  /^(cargo\.toml|go\.mod|pyproject\.toml|requirements\.txt|gemfile|pom\.xml|build\.gradle(\.kts)?)$/i,
  /^prisma\/schema\.prisma$/,
  /^(next|vite|nuxt|astro|svelte|remix|tailwind|webpack|rollup|tsup)\.config\.(js|mjs|cjs|ts)$/,
  /^tsconfig\.json$/,
  /^(dockerfile|docker-compose\.ya?ml|makefile)$/i,
  /^src\/(main|index|app)\.(ts|tsx|js|jsx|py|rs|go)$/,
  /^(main|index|app|server)\.(ts|tsx|js|jsx|py|rs|go)$/,
  /^\.env\.example$/,
];

const inFlight = new Set<string>();

/** How many graphify runs are active right now — the API route uses this as
 * a global cap so a burst of clicks can't stampede GitHub + the key pool. */
export function activeIndexCount(): number {
  return inFlight.size;
}

interface TreeEntry {
  path: string;
  type: string;
  size?: number;
}

async function llm(prompt: string): Promise<string | null> {
  const tries = Math.max(1, poolSize());
  for (let i = 0; i < tries; i++) {
    const key = nextGeminiKey();
    if (!key) return null;
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${DOC_MODEL}:generateContent?key=${key}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [{ role: "user", parts: [{ text: prompt }] }],
            // thinkingBudget 0: on the 2.5 series, thinking is on by default
            // and thought tokens count INSIDE maxOutputTokens — big analytical
            // prompts like these would otherwise burn the whole budget
            // thinking and return zero visible text.
            generationConfig: { temperature: 0.3, maxOutputTokens: 3000, thinkingConfig: { thinkingBudget: 0 } },
          }),
        }
      );
      if (!res.ok) {
        if (res.status === 429 || res.status >= 500) {
          reportGeminiKeyError(key);
          continue;
        }
        return null;
      }
      const data = await res.json();
      const text =
        data?.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text ?? "").join("") ?? "";
      return text || null;
    } catch {
      reportGeminiKeyError(key);
    }
  }
  return null;
}

async function fetchFileContent(ownerRepo: string, path: string): Promise<string | null> {
  const data = (await ghJson(
    `https://api.github.com/repos/${ownerRepo}/contents/${encodeURIComponent(path).replace(/%2F/g, "/")}`
  )) as { content?: string; encoding?: string; size?: number } | null;
  if (!data?.content || data.encoding !== "base64") return null;
  try {
    return Buffer.from(data.content, "base64").toString("utf-8").slice(0, MAX_FILE_BYTES);
  } catch {
    return null;
  }
}

function pickKeyFiles(paths: string[]): string[] {
  const picked: string[] = [];
  for (const pattern of KEY_FILE_PATTERNS) {
    for (const p of paths) {
      if (picked.length >= MAX_KEY_FILES) return picked;
      if (pattern.test(p.toLowerCase()) && !picked.includes(p)) picked.push(p);
    }
  }
  return picked;
}

/** Top-level "modules" (directories) ranked by file count — the graph nodes. */
function moduleGroups(paths: string[]): Map<string, string[]> {
  const groups = new Map<string, string[]>();
  for (const p of paths) {
    const seg = p.includes("/") ? p.slice(0, p.indexOf("/")) : "(root)";
    if (!groups.has(seg)) groups.set(seg, []);
    groups.get(seg)!.push(p);
  }
  return new Map([...groups.entries()].sort((a, b) => b[1].length - a[1].length));
}

/** Small representative source files from a module, for the LLM's deep dive. */
function sampleFiles(files: string[], entries: Map<string, number>): string[] {
  const sourceish = files.filter((f) => /\.(ts|tsx|js|jsx|py|rs|go|java|rb|prisma|sql)$/.test(f));
  return sourceish
    .filter((f) => (entries.get(f) ?? Infinity) <= MAX_FILE_BYTES)
    .sort((a, b) => a.split("/").length - b.split("/").length) // shallower = more central
    .slice(0, MAX_MODULE_SAMPLE_FILES);
}

export async function graphifyRepo(slug: string, repoUrl: string): Promise<void> {
  if (inFlight.has(slug)) return;
  inFlight.add(slug);
  try {
    const parsed = parseOwnerRepo(repoUrl);
    if (!parsed) {
      await setRepoIndexRow(slug, { repoUrl, status: "error", error: "Not a github.com repo URL." });
      return;
    }
    const key = `${parsed.owner}/${parsed.repo}`;
    await setRepoIndexRow(slug, { repoUrl, status: "indexing" });

    const meta = (await ghJson(`https://api.github.com/repos/${key}`)) as {
      description?: string | null;
      language?: string | null;
      default_branch?: string;
      topics?: string[];
    } | null;
    if (!meta) {
      await setRepoIndexRow(slug, {
        repoUrl,
        status: "error",
        error: "Repo unreachable — private, deleted, or GitHub rate-limited (set GITHUB_TOKEN for 5000 req/hr).",
      });
      return;
    }

    const [readmeData, treeData] = await Promise.all([
      ghJson(`https://api.github.com/repos/${key}/readme`) as Promise<{ content?: string } | null>,
      ghJson(`https://api.github.com/repos/${key}/git/trees/${meta.default_branch ?? "main"}?recursive=1`) as Promise<{
        tree?: TreeEntry[];
      } | null>,
    ]);

    let readme = "";
    if (readmeData?.content) {
      try {
        readme = Buffer.from(readmeData.content, "base64").toString("utf-8").slice(0, 12000);
      } catch {
        /* unreadable readme — proceed without */
      }
    }

    const blobs = (treeData?.tree ?? []).filter((e) => e.type === "blob");
    const sizeByPath = new Map(blobs.map((e) => [e.path, e.size ?? Infinity]));
    const allPaths = blobs
      .map((e) => e.path)
      .filter((p) => !/(^|\/)(node_modules|\.git|dist|build|\.next|out|vendor|__pycache__|target)\//.test(p));
    const paths = allPaths.slice(0, MAX_TREE_PATHS);

    // ── raw key-file contents (manifests, configs, entry points) ──
    // matched against the FULL tree, not the capped slice — the git trees
    // API lists depth-first alphabetically, so on an 800+-file repo the
    // root package.json would otherwise fall outside the window and the
    // stack doc would go blind on exactly the repos that matter most.
    const keyFilePaths = pickKeyFiles(allPaths);
    const keyFiles: { path: string; content: string }[] = [];
    for (const p of keyFilePaths) {
      const content = await fetchFileContent(key, p);
      if (content) keyFiles.push({ path: p, content });
    }
    const manifestBlock = keyFiles.map((f) => `=== ${f.path} ===\n${f.content}`).join("\n\n");

    const groups = moduleGroups(allPaths);
    const moduleSummaryLines = [...groups.entries()]
      .map(([name, files]) => `${name} — ${files.length} files`)
      .join("\n");

    const docs: RepoDoc[] = [];

    // ── LLM docs — each independent, a failure just skips that doc ──
    const overview = await llm(
      [
        `You are documenting the GitHub repo ${key} (${meta.description ?? "no description"}) so an on-site AI assistant can answer visitor questions about it accurately.`,
        `Write an "Architecture overview" doc: what the system does, how it's structured, the main runtime flow, and where the interesting engineering lives. Be concrete and specific to THIS repo — never generic filler. Use the evidence below only; if something isn't evidenced, don't claim it.`,
        readme ? `README:\n${readme}` : null,
        manifestBlock ? `Key files:\n${manifestBlock.slice(0, 20000)}` : null,
        `Top-level structure:\n${moduleSummaryLines}`,
        `File tree (partial):\n${paths.slice(0, 300).join("\n")}`,
      ]
        .filter(Boolean)
        .join("\n\n")
    );
    if (overview) docs.push({ title: "Architecture overview", content: overview });

    const stack = await llm(
      [
        `From these manifest/config files of the GitHub repo ${key}, write a "Tech stack & dependencies" doc: languages, frameworks, notable libraries and what each is used for, build/deploy tooling, and any services it talks to (DBs, APIs). Concrete and evidence-based only.`,
        manifestBlock ? manifestBlock.slice(0, 20000) : `(no manifests readable — primary language: ${meta.language ?? "unknown"})`,
      ].join("\n\n")
    );
    if (stack) docs.push({ title: "Tech stack & dependencies", content: stack });

    const moduleEntries = [...groups.entries()].filter(([, files]) => files.length >= 3).slice(0, MAX_MODULE_DOCS);
    for (const [name, files] of moduleEntries) {
      const samples: string[] = [];
      for (const f of sampleFiles(files, sizeByPath)) {
        const content = await fetchFileContent(key, f);
        if (content) samples.push(`=== ${f} ===\n${content}`);
      }
      const moduleDoc = await llm(
        [
          `Document the "${name}" module of the GitHub repo ${key} for an AI assistant answering questions about the codebase. What lives here, what it's responsible for, how its pieces relate. Evidence-based, specific, no filler.`,
          `Files in this module:\n${files.slice(0, 120).join("\n")}`,
          samples.length ? `Sampled sources:\n${samples.join("\n\n").slice(0, 16000)}` : null,
        ]
          .filter(Boolean)
          .join("\n\n")
      );
      if (moduleDoc) docs.push({ title: `Module: ${name}`, content: moduleDoc });
    }

    // ── raw docs — always present, even if every LLM call failed ──
    docs.push({
      title: "File tree",
      content: [
        `${key} — ${meta.language ?? "?"}${meta.topics?.length ? ` · ${meta.topics.join(", ")}` : ""}`,
        `${blobs.length} files total, showing ${paths.length}:`,
        paths.join("\n"),
      ].join("\n"),
    });
    if (readme) docs.push({ title: "README", content: readme });
    if (manifestBlock) docs.push({ title: "Key files (verbatim)", content: manifestBlock });

    await setRepoIndexRow(slug, { repoUrl, status: "ready", docs });
  } catch (e) {
    console.error("repo-indexer: graphify failed:", e);
    await setRepoIndexRow(slug, {
      repoUrl,
      status: "error",
      error: e instanceof Error ? e.message : "indexing failed",
    });
  } finally {
    inFlight.delete(slug);
  }
}
